- include: apt.yml
  tags: [packages]
  when: ansible_pkg_mgr == "apt"

- include: yum.yml
  tags: [packages]
  when: ansible_pkg_mgr == "yum"

- include: zypper.yml
  tags: [packages]
  when: ansible_pkg_mgr == "zypper"
