- name: zypper | add/remove package repos
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
  with_items: '{{ packages_repos }}'

- name: zypper | remove packages
  zypper:
    name: "{{ item }}"
    state: absent
  with_items: '{{ packages_remove }}'

- name: zypper | update cache and add packages
  zypper:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items: '{{ packages_add }}'
